name: Deploy Production Environment

on:
  push:
    branches:
      - main  # Ce workflow s'exécute uniquement pour la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages (Production)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Dossier source, racine du dépôt
          destination_dir: .  # Déploie les fichiers dans la racine de gh-pages